### ISSUE TITLE
PoC with OpenAirInterface (OAI) SPGWu 

### ISSUE THREAD

**Issue by navarrothiago** [navarrothiago/upf-bpf#44]
Because the upf-bpf is a C++ library, a good candidate to do this integration is the OpenAirInterface's SPGWu, which is also implemented using C++. Here is some suggestion of task for this PoC:

- [ ]  Deploy the [OAI spgwu](https://github.com/OPENAIRINTERFACE/openair-spgwu-tiny)
- [ ]  Create/Find a component to send the PFCP messages to spgwu [1][2]
- [ ]  Test OAI with the setup below
- [ ]  Compile the OAI with upf-bpf library
- [ ]  Test OAI + upf-bpf with the same setup

[1] -  I didnt find any open source tool that could be a PFPC client (e.g. [here](https://www.synopsys.com/software-integrity/security-testing/fuzz-testing/defensics/protocols/pfcp-client.html)).
[2] - I have some hardcoded implementation. Check [here](https://github.com/navarrothiago/openair-cn-cups/blob/develop-spgwu/test/integration/spgwu_tests.cpp#L140-L210). The idea is to inject the ITTI messages in SPGWu. The ITTI is a m

The test case description is defined [here](https://github.com/navarrothiago/openair-cn-cups/issues/1).

![image](https://user-images.githubusercontent.com/42647168/129460397-391b4918-9816-46f2-b85b-6081979e8864.png)

**Comment by infinitydon** [comment]
@navarrothiago - First of all I appreciate the effort you are putting into this project..

I am currently learning about various 5G userplane acceleration projects with emphasis on using Kubernetes for orchestration.

I will suggest Open5gs to test the integration but from my experience with trying to integrate it with travel-ping upg-vpp, there is no uniform conformance to standards, up till now I am still not able to make Open5gs work with upg-vpp (mostly because I am not a software developer but I have started to learn C since it seems that is the logical for me to get most of the implementations to work)..

You can check the following issue for the open5gs and upg-vpp discussion maybe it will give you an idea maybe upf-bpf will work with Open5gs SMF "https://github.com/travelping/upg-vpp/issues/101".

But I am available to test your implementation using Open5gs and Kubernetes.

Can you kindly provide how to implement this? I think the Dockerfile also needs to be optimized as per the number of layers, I think some of the commands can be combined to reduce the layers unless there is a specific reason you are building it this way..

**Comment by navarrothiago** [comment]
@infinitydon, really nice!! There is a lot of good discussion on the issue that you have pointed out. Thanks for sharing it. 

Regarding to the PoC, let me put some background: this project is a C++ library the manages the eBPF programs related to the PFCP sessions. Because of that, I believe the integration with Open5Gs wont possible for while, because the UPF was implemented in C right? We would needed to extend the API for C. Because the OAI was implemented using C++, it is a good starting point. I have already done some initial integration before. But the core changed and a new validation is needed. 
I can provide more details with you are interested with.

Regarding the dockerfile, the idea was to create a development environment to make it ease the development :smile:

**Comment by infinitydon** [comment]
Thanks for the response @navarrothiago - I have also tested OAI Core components i.e. AMF, NRF, SMF, SPGWU on Kubernetes so I can work with OAI too.

I am not clear about your comment on Open5gs, I believe your project is an implementation for UPF? Since Open5gs SMF will communicate via PFCP with your UPF, I don't think there is need to write a separate API just for Open5gs, kindly correct me if my assumption is wrong..

**Comment by infinitydon** [comment]
Sorry I understand better, this will be an enhancement to existing/3rd party UPF solutions by offloading some of the processes to eBPF, this means you will have to adapt it to the individual code design i.e. the API?

You can share more details about the OAI SPGWU integration.

**Comment by navarrothiago** [comment]
@infinitydon Glad to know that you found the answer. Sure!! Let me think about it. This weekend I will update this issue with more details.

**Comment by navarrothiago** [comment]
@infinitydon, description updated. Please, let me know if you have any question.

**Comment by navarrothiago** [comment]
I have migrated this discussion to here - https://github.com/navarrothiago/upf-bpf/discussions/52
